import readlineSync from "readline-sync";
import { GoogleGenAI } from "@google/genai";
import * as dotenv from "dotenv";
import { GoogleGenerativeAIEmbeddings } from "@langchain/google-genai";
import { Pinecone } from "@pinecone-database/pinecone";

dotenv.config();

const ai = new GoogleGenAI({});
const History = [];

async function transformQuery(userQuery) {
  console.log("[INFO] Rewriting query into a standalone user question...");

  History.push({
    role: "user",
    parts: [{ text: userQuery }],
  });

  const response = await ai.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: History,
    config: {
        systemInstruction: `You are an expert prompt engineer and query rewriting specialist.
        Based on the chat history, rewrite the user's follow-up question into a complete, standalone question.
        The rewritten question must be clear, self-contained, and preserve the original technical intent.
        Output only the rewritten question with no additional commentary.
        `,
    },
  });

  console.log("[INFO] Query rewrite complete.");
  History.pop();

  return response.text.trim();
}

async function chatting(userQuery) {
  // // <-- Convert the user query into query vector -->

  // const ai = new GoogleGenAI({
  //     apiKey: process.env.GEMINI_API_KEY
  // });

  // const response = await ai.models.embedContent({
  //     model: 'gemini-embedding-001',
  //     contents: userQuery,
  // }); // 3072 dimensional vector

  // console.log(response.embeddings)
  // console.log(response.embeddings[0].values.length)

  // OR
  console.log("[INFO] Starting query transformation and retrieval flow...");
  const transformedQuery = await transformQuery(userQuery);
  const embeddings = new GoogleGenerativeAIEmbeddings({
    apiKey: process.env.GEMINI_API_KEY,
    model: "gemini-embedding-001",
  });

  console.log("[INFO] Generating semantic embedding for the transformed query...");
  const queryVector = await embeddings.embedQuery(transformedQuery);

  console.log("[INFO] Query vector generation complete.");
  // console.log(queryVector);

  // // <-- Query the vector DB - get the relevant chunks -->
  const pc = new Pinecone();

  const index = pc.Index(process.env.PINECONE_INDEX_NAME);

  console.log("[INFO] Querying Pinecone for the top relevant chunks...");
  const queryResponse = await index.query({
    vector: queryVector,
    topK: 10,
    includeMetadata: true,
  });

  console.log("[INFO] Relevant chunk querying completed.");
  // console.log(queryResponse);

  const context = queryResponse.matches
    .map((match) => match.metadata.text)
    .join("\n\n---\n\n");

  console.log("[INFO] Constructed context from retrieved chunks.");
  // console.log(context);

  // // <-- Feed the above chunks to the LLM -->
  History.push({
    role: "user",
    parts: [{ text: transformedQuery }],
  });

  const response = await ai.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: History,
    config: {
        systemInstruction: `You are an expert Data Structures and Algorithms tutor.
        You will be provided with retrieved context and a user question.
        Only use the supplied context to answer the question.
        If the answer is not contained in the context, respond exactly: "I could not find the answer in the provided document."
        Keep responses concise, accurate, and educational.
        Only include examples or code when the context directly supports them.

        Context:
        ${context}
        `,
    },
  });

  console.log("[INFO] Final response generated by the model.");
  console.log("\n=== Final Response ===\n", response.text.trim(), "\n");

  History.push({
    role: "model",
    parts: [{ text: response.text }],
  });
}

async function main() {
  const userQuery = readlineSync.question("\n<-- I am your DSA Instructor. Ask me anything related to DSA :) -->\n\n");
  await chatting(userQuery);
  main();
}

main();
